version: "3.8"

services:
  service-desk-mysql:
    image: mysql:8.4.0
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
      # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      timeout: 20s
      retries: 10

  service-desk-backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput  && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - service-desk-mysql
    env_file:
      - .env

  chromadb:
    image: chromadb/chroma
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./rag/data/chroma-data:/chroma/chroma

  rag-pipeline:
    build:
      context: .
      dockerfile: rag/src/rag_pipeline/Dockerfile
    restart: unless-stopped
    depends_on:
      - chromadb
    env_file:
      - rag/config/giga_chat_api.env
    ports:
      - "8085:8085"
    volumes:
      - ./rag/src/rag_pipeline/:/opt/app-root/rag/src/rag_pipeline:rw
      - ./rag/src/embeddings/:/opt/app-root/rag/src/embeddings:rw
      - ./rag/src/file_processing/:/opt/app-root/rag/src/file_processing:rw
      - ./rag/src/giga_chat/:/opt/app-root/rag/src/giga_chat:rw
      - ./rag/not_included_data/:/opt/app-root/rag/not_included_data:rw
volumes:
  data:
  chroma-data:
    driver: local
