# Generated by Django 5.0.1 on 2024-04-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_attribute_custompermission_emailsettings_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetattribute',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetattribute',
            name='value_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='assetattribute',
            name='value_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetattribute',
            name='value_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Логический'), ('email', 'Электронная почта'), ('url', 'Ссылка'), ('json', 'JSON'), ('asset_ref', 'Ссылка на актив'), ('attr_ref', 'Ссылка на атрибут')], max_length=50),
        ),
    ]
