# Generated by Django 5.0.2 on 2024-05-26 18:30

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0004_assettypeattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('analyzed', models.BooleanField(default=False)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_urls', models.TextField(blank=True, null=True)),
                ('tables', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('create_request', 'Создание заявки'), ('update_request', 'Изменение полей заявки'), ('add_comment', 'Добавление комментария'), ('deadline_expiration', 'Истечение срока заявки'), ('status_change', 'Смена статуса заявки')], max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_template', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='auth.group')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupEventNotification',
        ),
    ]
