# Generated by Django 5.0.2 on 2024-05-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_add_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='access_level',
            field=models.CharField(blank=True, choices=[('personal', 'Только свои'), ('department', 'Своего отдела'), ('department_with_subs', 'Своего отдела с дочерним'), ('company', 'Своей компании'), ('global', 'Все заявки')], max_length=50, null=True),
        ),
    ]
