# Generated by Django 4.2.5 on 2023-10-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_priority_requesttype_status_request_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorityduration',
            name='duration',
        ),
        migrations.AddField(
            model_name='priorityduration',
            name='duration_in_hours',
            field=models.IntegerField(default=0),
        ),
    ]
