# Generated by Django 5.0.1 on 2024-06-25 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0006_notificationtemplate_alter_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='request',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='request',
            name='company',
        ),
        migrations.RemoveField(
            model_name='request',
            name='description',
        ),
        migrations.RemoveField(
            model_name='request',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='title',
        ),
        migrations.CreateModel(
            name='FieldMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('status', 'Status'), ('company', 'Company'), ('priority', 'Priority'), ('requester', 'Requester'), ('assignee', 'Assignee'), ('request_type', 'Request Type')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('show_name', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('hint', models.CharField(blank=True, max_length=255, null=True)),
                ('request_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='field_metas', to='service.requesttype')),
            ],
        ),
        migrations.CreateModel(
            name='FieldAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('field_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.fieldmeta')),
            ],
        ),
        migrations.AddField(
            model_name='requesttype',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='request_types', to='service.fieldmeta'),
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('value_url', models.URLField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('field_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.fieldmeta')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='service.request')),
                ('value_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_assignee', to=settings.AUTH_USER_MODEL)),
                ('value_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.company')),
                ('value_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.priority')),
                ('value_request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.requesttype')),
                ('value_requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_requester', to=settings.AUTH_USER_MODEL)),
                ('value_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.status')),
            ],
        ),
    ]
