# Generated by Django 4.2.5 on 2023-10-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_priorityduration_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Создана'), ('updated', 'Обновлена'), ('status_changed', 'Статус изменен'), ('comment_added', 'Комментарий добавлен')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='service.request')),
            ],
        ),
    ]
