# Generated by Django 5.0.1 on 2024-06-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmeta',
            name='request_type',
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='value_file',
            field=models.FileField(blank=True, null=True, upload_to='field_files/'),
        ),
        migrations.AlterField(
            model_name='fieldmeta',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('status', 'Status'), ('company', 'Company'), ('priority', 'Priority'), ('requester', 'Requester'), ('assignee', 'Assignee'), ('request_type', 'Request Type'), ('file', 'File')], max_length=50),
        ),
    ]
