# Generated by Django 5.0.1 on 2024-06-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_fieldmeta_request_type_fieldvalue_value_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='request',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='fields',
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.requesttype'),
        ),
        migrations.CreateModel(
            name='FieldSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.ManyToManyField(blank=True, related_name='field_sets', to='service.fieldmeta')),
            ],
        ),
        migrations.AddField(
            model_name='requesttype',
            name='field_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.fieldset'),
        ),
    ]
