# Generated by Django 4.2.5 on 2023-10-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0008_lifecycleevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_groups', models.ManyToManyField(to='auth.group')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transitions', to='service.status')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transitions', to='service.status')),
            ],
            options={
                'unique_together': {('from_status', 'to_status')},
            },
        ),
        migrations.DeleteModel(
            name='LifecycleEvent',
        ),
    ]
