# Generated by Django 5.0.1 on 2024-07-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0009_remove_request_attachment_remove_request_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='event',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='email_template',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
