# Generated by Django 5.0.1 on 2024-07-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_notificationsetting_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='email_template',
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.notificationtemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='event',
            field=models.CharField(choices=[('create_request', 'Создание заявки'), ('update_request', 'Изменение полей заявки'), ('add_comment', 'Добавление комментария'), ('deadline_expiration', 'Истечение срока заявки'), ('status_change', 'Смена статуса заявки')], max_length=50),
        ),
    ]
