# Generated by Django 4.2.5 on 2023-10-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_savedfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='completed',
        ),
    ]
