# Generated by Django 5.0.1 on 2024-07-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_notificationsetting_email_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.notificationtemplate'),
        ),
    ]
