# Generated by Django 5.0.1 on 2024-07-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_notificationsetting_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='template',
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='service.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='push_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_templates', to='service.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='service.notificationtemplate'),
        ),
    ]
