# Generated by Django 4.2.5 on 2023-11-03 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_department_parent_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
