# Generated by Django 5.0.1 on 2024-07-08 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_notificationsetting_email_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='template',
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='service.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='push_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_settings', to='service.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_settings', to='service.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='telegram_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_settings', to='service.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='whatsapp_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_settings', to='service.notificationtemplate'),
        ),
    ]
