# Generated by Django 4.2.5 on 2023-11-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_customuser_department_department_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='employees',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.department'),
        ),
    ]
