# Generated by Django 4.2.5 on 2023-11-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_remove_department_employees_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
