# Generated by Django 5.0.1 on 2024-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_remove_notificationsetting_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='access_level',
            field=models.CharField(choices=[('personal', 'Personal'), ('department', 'Department'), ('global', 'Global')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='code_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldmeta',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('status', 'Status'), ('company', 'Company'), ('priority', 'Priority'), ('requester', 'Requester'), ('assignee', 'Assignee'), ('request_type', 'Request Type'), ('file', 'File'), ('comment', 'Comment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='event',
            field=models.CharField(choices=[('create_request', 'Создание заявки'), ('update_request', 'Изменение полей заявки'), ('add_comment', 'Добавление комментария'), ('deadline_expiration', 'Истечение срока заявки')], max_length=50),
        ),
    ]
