# Generated by Django 5.0.1 on 2024-08-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_grouppermission_access_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppermission',
            old_name='access_level',
            new_name='ACCESS_LEVEL_CHOICES',
        ),
    ]
