# Generated by Django 4.2.5 on 2023-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_comment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
