# Generated by Django 4.2.5 on 2023-11-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_request_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statustransition',
            old_name='allowed_groups',
            new_name='allowed_group',
        ),
    ]
