# Generated by Django 5.0.1 on 2024-08-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_rename_access_level_grouppermission_access_level_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppermission',
            old_name='ACCESS_LEVEL_CHOICES',
            new_name='access_level',
        ),
        migrations.RenameField(
            model_name='grouppermission',
            old_name='custompermission',
            new_name='permission',
        ),
    ]
