# Generated by Django 5.0.1 on 2024-08-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_rename_access_level_choices_grouppermission_access_level_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomPermission',
            new_name='Permission',
        ),
    ]
