# Generated by Django 5.0.1 on 2024-08-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_rename_custompermission_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='CustomPermission',
        ),
        migrations.RenameField(
            model_name='grouppermission',
            old_name='permission',
            new_name='custompermission',
        ),
    ]
