# Generated by Django 5.0.1 on 2024-08-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_rename_permission_custompermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='group',
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='functional_role',
            field=models.CharField(blank=True, choices=[('requester', 'Заявитель'), ('assignee', 'Исполнитель')], max_length=50, null=True),
        ),
    ]
