# Generated by Django 5.0.1 on 2024-08-23 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0021_remove_notificationsetting_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFieldMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('file', 'File')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='FieldAccess',
            new_name='RequestFieldAccess',
        ),
        migrations.RenameModel(
            old_name='FieldMeta',
            new_name='RequestFieldMeta',
        ),
        migrations.RenameModel(
            old_name='FieldSet',
            new_name='RequestFieldSet',
        ),
        migrations.RenameModel(
            old_name='FieldValue',
            new_name='RequestFiledValue',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ceo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='company',
            name='deputy',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='region',
        ),
        migrations.RemoveField(
            model_name='company',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.CreateModel(
            name='CompanyCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('file', 'File')], max_length=50)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('value_url', models.URLField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='company_custom_field_files/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_custom_fields', to='service.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFieldSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.ManyToManyField(blank=True, related_name='company_field_sets', to='service.companyfieldmeta')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('value_url', models.URLField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='company_field_files/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_field_values', to='service.company')),
                ('company_field_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.companyfieldmeta')),
            ],
        ),
    ]
