# Generated by Django 5.0.1 on 2024-08-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_remove_companyfieldset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfieldvalue',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
