# Generated by Django 5.0.1 on 2024-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_companyfieldvalue_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hidden_fields',
            field=models.ManyToManyField(blank=True, related_name='hidden_for_companies', to='service.companyfieldmeta'),
        ),
    ]
