# Generated by Django 5.0.1 on 2024-09-04 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_company_hidden_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название справочника')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.book', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочников',
                'unique_together': {('reference', 'value')},
            },
        ),
        migrations.CreateModel(
            name='CompanyCustomFieldMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('file', 'File')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_meta', to='service.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='hidden_custom_fields',
            field=models.ManyToManyField(blank=True, related_name='hidden_custom_for_companies', to='service.companycustomfieldmeta'),
        ),
        migrations.CreateModel(
            name='CompanyCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('value_url', models.URLField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='custom_field_files/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='service.company')),
                ('custom_field_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.companycustomfieldmeta')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyCustomField',
        ),
    ]
