# Generated by Django 4.2.5 on 2023-11-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_rename_permission_custompermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermission',
            name='requires_access_level',
            field=models.BooleanField(default=True),
        ),
    ]
