# Generated by Django 5.0.1 on 2024-09-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_book_bookitem_companycustomfieldmeta_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Reference',
        ),
        migrations.RenameModel(
            old_name='BookItem',
            new_name='ReferenceItem',
        ),
    ]
