# Generated by Django 4.2.5 on 2023-11-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_custompermission_requires_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompermission',
            name='requires_access_level',
            field=models.BooleanField(default=False),
        ),
    ]
