# Generated by Django 5.0.1 on 2024-09-05 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_rename_book_reference_rename_bookitem_referenceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycustomfieldvalue',
            name='value_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.referenceitem'),
        ),
        migrations.AddField(
            model_name='companyfieldmeta',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.reference', verbose_name='Справочник'),
        ),
        migrations.AddField(
            model_name='companyfieldvalue',
            name='value_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.referenceitem'),
        ),
        migrations.AlterField(
            model_name='companycustomfieldmeta',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('file', 'File'), ('reference', 'Reference')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyfieldmeta',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('file', 'File'), ('reference', 'Reference')], max_length=50),
        ),
    ]
