# Generated by Django 4.2.5 on 2023-11-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_rename_custompermission_grouppermission_custom_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppermission',
            old_name='custom_permission',
            new_name='custompermission',
        ),
        migrations.RemoveField(
            model_name='custompermission',
            name='requires_access_level',
        ),
    ]
