# Generated by Django 4.2.5 on 2023-11-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_custompermission_requires_access_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppermission',
            old_name='custompermission',
            new_name='custom_permission',
        ),
        migrations.RemoveField(
            model_name='custompermission',
            name='requires_access_level',
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='access_level',
            field=models.CharField(blank=True, choices=[('global', 'Global'), ('company', 'Company'), ('department', 'Department'), ('personal', 'Personal')], max_length=50, null=True),
        ),
    ]
