# Generated by Django 5.0.1 on 2024-09-05 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_companycustomfieldvalue_value_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycustomfieldmeta',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.reference', verbose_name='Справочник'),
        ),
    ]
