# Generated by Django 4.2.5 on 2024-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_rename_custom_permission_grouppermission_custompermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('login', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('email_from', models.EmailField(max_length=254)),
            ],
        ),
    ]
