# Generated by Django 5.0.1 on 2024-09-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_companycustomfieldmeta_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetattribute',
            name='value_boolean',
        ),
        migrations.RemoveField(
            model_name='assetattribute',
            name='value_date',
        ),
        migrations.RemoveField(
            model_name='assetattribute',
            name='value_email',
        ),
        migrations.RemoveField(
            model_name='assetattribute',
            name='value_json',
        ),
        migrations.RemoveField(
            model_name='assetattribute',
            name='value_number',
        ),
        migrations.RemoveField(
            model_name='assetattribute',
            name='value_text',
        ),
        migrations.RemoveField(
            model_name='assetattribute',
            name='value_url',
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('value_url', models.URLField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='service.asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.attribute')),
                ('value_asset_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_assets', to='service.asset')),
                ('value_attribute_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_attributes', to='service.attributevalue')),
            ],
        ),
    ]
