# Generated by Django 4.2.5 on 2024-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_emailsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='use_ssl',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='use_tls',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='connection_type',
            field=models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL')], default='tls', max_length=3),
        ),
    ]
