# Generated by Django 4.2.5 on 2024-01-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0030_remove_emailsettings_use_ssl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('email_template', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to='auth.group')),
            ],
        ),
    ]
