# Generated by Django 4.2.5 on 2024-01-19 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_groupeventnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'компания', 'verbose_name_plural': 'компании'},
        ),
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_ceo', to=settings.AUTH_USER_MODEL, verbose_name='Генеральный директор'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_contact_person', to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='company',
            name='deputy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_deputy', to=settings.AUTH_USER_MODEL, verbose_name='Заместитель генерального директора'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Регион'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='Часовой пояс'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название компании'),
        ),
    ]
