# Generated by Django 5.0.1 on 2024-03-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_asset_name_alter_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_types',
            new_name='asset_type',
        ),
    ]
